Desafio Csharp/Inicio/Gerenciamento/Gerenciamento/Controllers/TarefasController.cs
using Gerenciamento.Filters;
using Gerenciamento.Models;
using Gerenciamento.Repositorio;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Gerenciamento.Controllers
{
    [PaginaUsuarioLoged]
    public class TarefasController : Controller
    {
        private readonly ITarefaRepositorio _tarefaRepositorio;
        public TarefasController(ITarefaRepositorio tarefaRepositorio)
        {
            _tarefaRepositorio = tarefaRepositorio;
        }
        public IActionResult Index()
        {
            var tarefas = _tarefaRepositorio.BuscarTodos();
            return View(tarefas);
        }
        public IActionResult Criar()
        {
            return View();
        }
        public IActionResult Editar(int id)
        {
           var tarefas = _tarefaRepositorio.ListaPorId(id);
            return View(tarefas);
        }
        public IActionResult ApagarConfirmacao(int id)
        {
            var tarefas = _tarefaRepositorio.ListaPorId(id);
            return View(tarefas);
        }
        public IActionResult Apagar(int id)
        {
            _tarefaRepositorio.Apagar(id);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Criar(TarefaModel tarefa)
        {
            _tarefaRepositorio.Adicionar(tarefa);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Alterar(TarefaModel tarefa)
        {
            _tarefaRepositorio.Atualizar(tarefa);
            return RedirectToAction("Index");
        }
    }
}

Desafio Csharp/Inicio/Gerenciamento/Gerenciamento/Views/Tarefas/ApagarConfirmacao.cshtml
@model TarefaModel
@{
    ViewData["Title"] = "Apagar Tarefas";
}

<div class="text-center">

    <h3 > Realmente deseja apagar essa Tarefa?</h3>

</div>
<a class="btn btn-primary btn-block" role="button" asp-controller="Tarefas" asp-action="Index">Cancelar</a>
<a class="btn btn-danger btn-block" role="button"asp-controller="Tarefas" asp-route-id="@Model.id"  asp-action="Apagar" >Confirmar</a>

Desafio Csharp/Inicio/Gerenciamento/Gerenciamento/Views/Tarefas/Criar.cshtml
@model TarefaModel
@{
    ViewData["Title"] = "Criar Tarefas";
}

<div class="text-center">
    
    <h1 class="display-4"> Cadastrar Tarefas</h1>
    
</div>
<form asp-controller="Tarefas" asp-action="Criar" method="post">
    <div class="form-group">
        <label for="descricao">Descrição</label>
        <input type="text" asp-for="Descricao" class="form-control" placeholder="Digite uma Descrição...">
    </div>
    <div class="form-group">
        <label for="data/hora">Data e Hora</label>
        <input type="datetime-local" asp-for="Data_Hora" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Adicionar</button>
    <a  class="btn btn-secondary" asp-controller="Tarefas" asp-action="Index" role="button">Voltar</a>
</form>

Desafio Csharp/Inicio/Gerenciamento/Gerenciamento/Views/Tarefas/Editar.cshtml
@model TarefaModel
@{
    ViewData["Title"] = "Editar Tarefas";
}

<div class="text-center">

    <h1 class="display-4"> Editar Tarefas</h1>

</div>
<form asp-controller="Tarefas" asp-action="Alterar" method="post">
    <input type="hidden" asp-for="id"/>
    <div class="form-group">
        <label for="descricao">Descrição</label>
        <input type="text" asp-for="Descricao" class="form-control" placeholder="Digite uma Descrição...">
    </div>
    <div class="form-group">
        <label for="data/hora">Data e Hora</label>
        <input type="datetime-local" asp-for="Data_Hora" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Alterar</button>
    <a class="btn btn-secondary" asp-controller="Tarefas" asp-action="Index" role="button">Voltar</a>
</form>

Desafio Csharp/Inicio/Gerenciamento/Gerenciamento/Views/Tarefas/Index.cshtml
@model List<TarefaModel>
@{
    ViewData["Title"] = "Gerenciar Tarefas";
}

<div class="text-center">
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Tarefas" asp-action="Criar">Adicionar uma tarefa</a>
    </div>
        <br/>
    <h1 class="display-4"> Gerenciar Tarefas</h1>
    <table class="display" id="table-tarefas" style="width:100%">
        <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">Descrição</th>
                <th scope="col">Data/Hora</th>
                <th scope="col"></th>

            </tr>
        </thead>
        <tbody>
            @if(Model != null && Model.Any()){
                foreach(var tarefa in Model)
                {
            <tr>
                <th scope="row">@tarefa.id</th>
                <td>@tarefa.Descricao</td>
                <td>@tarefa.Data_Hora</td>
                <td>
                    <div class="btn-group" role="group">
                        <a role="button" class="btn btn-primary" asp-route-id="@tarefa.id" asp-controller="Tarefas" asp-action="Editar">Editar</a>

                        <a role="button" class="btn btn-danger" asp-route-id="@tarefa.id" asp-controller="Tarefas" asp-action="ApagarConfirmacao">Apagar</a>
                    </div>
                </td>

            </tr>
                }
            }
            

        </tbody>
    </table>

</div>